name: Deploy

on:
  push:
    branches:
      - niraj-working

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kisaan-portal" # Must be unique in Heroku
          heroku_email: "niraj.gujarathi1997@gmail.com"
          appdir: "backend"
        # env:
        #   HD_MONGODB_URI: ${{secrets.MONGODB_URI}}
        #   HD_PORT: ${{secrets.PORT}}
        #   HD_SECRET: ${{secrets.SECRET}}